VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

# ENCODERS
VIAL_ENCODERS_ENABLE = yes
ENCODER_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = no

RGBLIGHT_ENABLE = yes

BOOTMAGIC_ENABLE = lite
