EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

COMBO_ENABLE = no
CONSOLE_ENABLE = no
SWAP_HANDS_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no

LTO_ENABLE = yes
