VIA_ENABLE = yes
VIAL_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

VIAL_ENCODERS_ENABLE = yes
VIAL_INSECURE = yes

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = no

RGBLIGHT_ENABLE = yes

SWAP_HANDS_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = no

LTO_ENABLE = yes
